# file: $MLADP/util/nedc_evaluate_model/Makefile
#

# define source and object files
#
SRC = nedc_mladp_gen_graphics.py

# define an installation target
#
install:
	cp -f $(SRC) $(MLADP)/nedc_mladp/bin/$(SRC)
	cd $(MLADP)/nedc_mladp/bin; chmod u+rwx,g+rwx,o+rw $(SRC)

#
# end of file
